# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-13 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
